import { CONST-FUNCTION-GLOBAL } from "const_function.slint";
export component HanhKhach  inherits Rectangle {
    callback setData();
    in-out property <int> data;
    background: wheat;
    border-color: black;
    border-width: 12px;
    Rectangle {
        width: 100px;
        height: 100px;
        background: gray;
        Text {text: data; font-size: 24px;}
        t := TouchArea {
            clicked => {
                setData();
                CONST-FUNCTION-GLOBAL.SHOW_WARNING_ERORR("Canh Bao");
            }
        }
    }
}